#! /usr/bin/env python3
# -*- coding:utf-8 -*-

""" database table """

DTYPE_BASIC = '基础数据'
DTYPE_THIRD = '三方数据'
DB_TABLE_TYPE_ENUM = (DTYPE_BASIC, DTYPE_THIRD)

""" factor """

FTYPE_BASIC = '基础因子'
FTYPE_THIRD = '三方因子'
FACTOR_TYPE_ENUM = (FTYPE_BASIC, FTYPE_THIRD)

FTYPE_BASIC_PREFIX = 'JCYZ'
FTYPE_THIRD_PREFIX = 'SFYZ'

FACTOR_TYPES = {FTYPE_BASIC_PREFIX: FTYPE_BASIC, FTYPE_THIRD_PREFIX: FTYPE_THIRD}

FACTOR_CODE_PATTERN = r'^(?:JC|SF)YZ(\d+)$'
FACTOR_SUM_PATTERN = r''

STAT_UNKNOWN = '未启用'
STAT_ENABLE = '已启用'
STAT_DISABLE = '已停用'
FACTOR_STATUS_ENUM = (STAT_UNKNOWN, STAT_ENABLE, STAT_UNKNOWN)

STAT_UNKNOWN_CODE = 0
STAT_ENABLE_CODE = 1
STAT_DISABLE_CODE = 2

FACTOR_STATUSES = {STAT_UNKNOWN_CODE: STAT_UNKNOWN, STAT_ENABLE_CODE: STAT_ENABLE, STAT_DISABLE_CODE: STAT_DISABLE}

PARALLEL_CONTROL = '并行'
SERIAL_CONTROL = '串行'

PARALLEL_CODE = 1
SERIAL_CODE = 2

RISK_CONTROL_MODEL = {PARALLEL_CODE: PARALLEL_CONTROL, SERIAL_CODE: SERIAL_CONTROL}

OR_ROUTE = '与路由'
AND_ROUTE = '或路由'

AND_ROUTE_CODE = 2
OR_ROUTE_CODE = 1

ROUTE_MODEL = {AND_ROUTE_CODE: AND_ROUTE, OR_ROUTE_CODE: OR_ROUTE}

BTN_ENABLE = '启用'
BTN_DISABLE = '停用'

CONFIRM = '确定'
CANCEL = '取消'
